substitutions:
    devicename: blepresence

esphome:
  platform: ESP32
  board: nodemcu-32s

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

captive_portal:

ota:

mqtt:
    broker: nextpi.fritz.box
    topic_prefix: esphome/$devicename

esp32_ble_tracker:

binary_sensor:
  - platform: ble_presence
    mac_address: "B0:B4:48:F8:7E:C5"
    name: "Pebble Time Steel"
  - platform: ble_presence
    mac_address: "6E:3D:20:18:C6:83"
    name: "Pebble Time Steel 2"
