substitutions:
    devicename: doorbell

packages:
  wifi: !include fragments/common/wifi.config.yaml
  device_base: !include fragments/common/device_base.config.yaml

esphome:
  platform: ESP8266
  board: esp01_1m

captive_portal:

binary_sensor:
  - platform: gpio
    pin: GPIO2
    name: Doorbell
    device_class: sound
    filters:
      - invert:
      - delayed_off: 2s