substitutions:
    devicename: doorbell

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m
  build_path: build/$devicename

wifi:
  ssid: !secret ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$devicename"
    password: !secret ap_password

captive_portal:

# Enable logging
logger:

mqtt:
  broker: !secret mqtt_broker 
  topic_prefix: esphome/$devicename
  username: !secret mqtt_username
  password: !secret mqtt_password

binary_sensor:
  - platform: gpio
    pin: GPIO2
    name: Doorbell
    device_class: sound
    filters:
      - invert:
      - delayed_off: 2s