substitutions:
    devicename: doppler-radar

packages:
  wifi: !include fragments/common.wifi.config.yaml
  device_base: !include fragments/common.device_base.config.yaml

esphome:
  platform: ESP8266
  board: nodemcuv2

captive_portal:

mqtt:
  on_message:
    - topic: esphome/$devicename/curtain1/position
      then:
        - stepper.report_position:
              id: curtain1
              position: 0
        - stepper.set_target:
              id: curtain1
              target: !lambda return atoi(x.c_str());
    - topic: esphome/$devicename/curtain1/speed
      then:
        - stepper.set_speed:
              id: curtain1
              speed: !lambda return atoi(x.c_str());
    - topic: esphome/$devicename/curtain1/acceleration
      then:
      - stepper.set_acceleration:
          id: curtain1
          acceleration: !lambda return atoi(x.c_str());

output:
  - id: onboard_led
    platform: gpio
    pin: D4
    inverted: true

binary_sensor:
  - platform: gpio
    pin: D8
    name: "Doppler Motion"
    device_class: motion
    filters:
      - delayed_on: 2s
      - delayed_off: 10s
    on_press:
        then:
          - output.turn_on: onboard_led
    on_release:
        then:
          - output.turn_off: onboard_led

i2c:
  sda: D6
  scl: D5

font:
  - file: "fonts/comic.ttf"
    id: comicsans
    size: 10

animation:
  - file: resources/bongo-cat-smol.gif
    id: test_animation

display:
  - platform: ssd1306_i2c
    model: "SSD1306 64x48"
    lambda: |-
      id(test_animation).next_frame();
      id(test_animation).next_frame();
      it.image(0,0, id(test_animation), COLOR_ON, COLOR_OFF);


stepper:
  - platform: uln2003
    id: curtain1
    pin_a: D0
    pin_b: D1
    pin_c: D2
    pin_d: D3
    max_speed: 500 steps/s
    acceleration: 300 steps/s^2
    sleep_when_done: true