substitutions:
    devicename: growth_lamp 

packages:
  wifi: !include fragments/common/wifi.yaml
  device_base: !include fragments/common/device_base.yaml

esphome:
  platform: ESP8266
  board: nodemcuv2

wifi:
  manual_ip:
    static_ip: 192.168.144.182
    gateway: 192.168.144.1
    subnet: 255.255.255.0

logger:
  baud_rate: 0

mqtt:
  birth_message:
  will_message:

output:
  - platform: gpio
    pin: D2
    id: light_out

light:
  - platform: binary
    name: $devicename Light
    output: light_out
