substitutions:
    devicename: hydroponics
    temp_update: 600s
    pump_duration: "70"

esphome:
  name: $devicename
  platform: ESP32
  board: nodemcu-32s
  build_path: build/$devicename

wifi:
  ssid: !secret ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.144.180
    gateway: 192.168.144.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$devicename"
    password: !secret ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

mqtt:
    broker: !secret mqtt_broker 
    topic_prefix: esphome/$devicename
    username: !secret mqtt_username
    password: !secret mqtt_password
    birth_message:
    will_message:
    on_message:
      - topic: esphome/$devicename/pump_duration
        then:
          - lambda: |-
              id(pump_duration) = atoi(x.c_str());

globals:
  - id: pump_duration
    type: int
    restore_value: no
    initial_value: $pump_duration

script:
  - id: pump_and_wait
    mode: restart
    then:
      - logger.log:
          level: INFO
          format: "Pumping water for %u seconds."
          args: [ "id(pump_duration)" ]
      - delay: !lambda return id(pump_duration) * 1000;
      - switch.turn_off: water_pump
      - logger.log:
          level: INFO
          format: "Watering finished. Next watering in %f minutes."
          args: [ "id(pump_interval).state" ]
      - delay: !lambda return id(pump_interval).state * 60 * 1000;
      - switch.turn_on: water_pump

dallas:
  - pin: GPIO17
    update_interval: $temp_update

sensor:
  - platform: dht
    pin: GPIO21
    model: DHT22
    temperature:
        name: $devicename Outside Temperature
        id: outside_temperature
    humidity:
        name: $devicename Outside Humidity
        accuracy_decimals: 1
    update_interval: $temp_update
  - platform: adc
    pin: GPIO32
    attenuation: 11db
    name: $devicename Battery Voltage
    unit_of_measurement: "V"
    update_interval: 600s
    filters:
      - multiply: 5.7
      - calibrate_linear:
        - 9.4 -> 9
        - 10.6 -> 10
        - 11.74 -> 11
        - 13.5 -> 12
        - 14 -> 13
        - 15.2 -> 14
        - 16.45 -> 15
        - 18 -> 16
  - platform: dallas
    name: $devicename Water Temperature
    address: 0xE20120501EED9628
  - platform: template
    id: pump_interval
    name: $devicename Pump Interval
    icon: mdi:timer-outline
    unit_of_measurement: min
    accuracy_decimals: 0
    lambda: |-
        float temp = id(outside_temperature).state;
        int newval = 210;
        if (temp <= 10) newval = 210;
        if (temp > 10 && temp <= 15) newval = 180;
        if (temp > 15 && temp <= 20) newval = 120;
        if (temp > 20 && temp <= 25) newval = 90;
        if (temp > 25 && temp <= 30) newval = 60;
        if (temp > 30) newval = 30;
        if (newval != id(pump_interval).state) return newval;
        return {};

switch:
  - platform: gpio
    name: $devicename Water Pump
    id: water_pump
    pin: GPIO25
    on_turn_on:
      - script.execute: pump_and_wait
  - platform: template
    id: pump_automation_running
    name: $devicename Pump Automation Running
    icon: mdi:robot-industrial
    lambda: return id(pump_and_wait).is_running();
    turn_on_action:
      - switch.turn_on: water_pump
    turn_off_action:
      - script.stop: pump_and_wait
      - switch.turn_off: water_pump

time:
  - platform: homeassistant
