substitutions:
    devicename: hydroponics
    temp_update: 10s # todo: reduce this after testing
    pump_duration: "30" # todo: measure actual pump duration

esphome:
  name: $devicename
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$devicename"
    password: !secret ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

mqtt:
    broker: !secret mqtt_broker 
    topic_prefix: esphome/$devicename
    username: !secret mqtt_username
    password: !secret mqtt_password
    on_message:
      - topic: esphome/$devicename/pump_duration
        then:
          - lambda: |-
              id(pump_duration) = atoi(x.c_str());

globals:
  - id: pump_duration
    type: int
    restore_value: no
    initial_value: $pump_duration

script:
  - id: pump_and_wait
    mode: restart
    then:
      - logger.log:
          level: INFO
          format: "Pumping water for %u seconds."
          args: [ "id(pump_duration)" ]
      - delay: !lambda return id(pump_duration) * 1000;
      - switch.turn_off: water_pump
      - logger.log:
          level: INFO
          format: "Watering finished. Next watering in %f seconds."
          args: [ "id(pump_interval).state" ]
      - delay: !lambda return id(pump_interval).state * 1000;
      - switch.turn_on: water_pump

sensor:
  - platform: dht
    pin: GPIO5
    model: DHT22
    temperature:
        name: Outside Temperature
        id: outside_temperature
    humidity:
        name: Outside Humidity
        accuracy_decimals: 1
    update_interval: $temp_update
  - platform: template
    id: "pump_interval"
    name: "Pump Interval"
    lambda: |-
        float temp = id(outside_temperature).state;
        return temp * 10; // todo: remove this after testing
        if (temp <= 10) { return 210*60; }
        if (temp > 10 && temp <= 15) { return 180*60; }
        if (temp > 15 && temp <= 20) { return 120*60; }
        if (temp > 20 && temp <= 25) { return 90*60; }
        if (temp > 25 && temp <= 30) { return 60*60; }
        if (temp > 30) { return 30*60; }
        return 210*60;

switch:
  - platform: gpio
    name: "Water Pump"
    id: water_pump
    pin: GPIO2
    on_turn_on:
      - script.execute: pump_and_wait

time:
  - platform: homeassistant