substitutions:
  devicename:  loadcell

packages:
  wifi: !include fragments/common/wifi.yaml
  device_base: !include fragments/common/device_base.yaml

esphome:
  platform: ESP8266
  board: nodemcuv2

captive_portal:

sensor:
  - platform: hx711
    name: "HX711 Value"
    dout_pin: D1
    clk_pin: D2
    gain: 128
    update_interval: 1s
