substitutions:
  devicename: notification-test

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

external_components:
  - source:
      type: local
      path: components

esphome:
  platform: ESP8266
  board: d1_mini
#  on_boot:
#    priority: -200
#    then:
#      - light.turn_on:
#          id: notification_light
#          effect: "THE notification effect"

time:
  - platform: sntp
    id: sntp_time

notification_light:
  colors:
  - red
  - green
  - blue
