substitutions:
  devicename: planter 

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

esphome:
  platform: ESP8266
  board: esp01

# Enable logging
logger:
  baud_rate: 0
  tx_buffer_size: 128
  esp8266_store_log_strings_in_flash: False

mqtt:
    birth_message:
    will_message:

output:
  - platform: gpio
    pin: 2
    id: light_out
    #    inverted: True

light:
  - platform: binary
    name: $devicename Light
    output: light_out
