substitutions:
    devicename: planter 

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01

wifi:
  ssid: !secret ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$devicename"
    password: !secret ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

mqtt:
    broker: !secret mqtt_broker 
    topic_prefix: esphome/$devicename
    username: !secret mqtt_username
    password: !secret mqtt_password

output:
  - platform: gpio
    pin: 2
    id: gpio_2

light:
  - platform: binary
    name: "Planter Light"
    output: gpio_2
