substitutions:
    devicename: planter 

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01
  build_path: build/$devicename

wifi:
  ssid: !secret ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$devicename"
    password: !secret ap_password

# Enable logging
logger:
  baud_rate: 0
  tx_buffer_size: 128
  esp8266_store_log_strings_in_flash: False

ota:

mqtt:
    broker: !secret mqtt_broker 
    topic_prefix: esphome/$devicename
    username: !secret mqtt_username
    password: !secret mqtt_password
    birth_message:
    will_message:

output:
  - platform: gpio
    pin: 1
    id: light_out
    inverted: True

light:
  - platform: binary
    name: $devicename Light
    output: light_out
