substitutions:
    devicename: rotenc

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

esphome:
  platform: ESP8266
  board: nodemcuv2

captive_portal:

sensor:
  - platform: rotary_encoder
    name: "Rotary Encoder"
    pin_a: D7
    pin_b: D8