substitutions:
  devicename:  servotest

packages:
  wifi: !include fragments/common.wifi.config.yaml
  device_base: !include fragments/common.device_base.config.yaml

esphome:
  platform: ESP32
  board: nodemcu-32s

captive_portal:

mqtt:
  on_message:
    topic: esphome/$devicename/servo1/command
    then:
      - servo.write:
          id: servo1
          level: !lambda "return atof(x.c_str());"

servo:
  - id: servo1
    output: pwm1
    #min_level: 3%
    #idle_level: 8%
    #max_level: 13%

output:
  - id: pwm1
    platform: ledc
    pin: GPIO19
    frequency: 50Hz