substitutions:
    devicename: staircase_leds

esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini
  build_path: build/$devicename

wifi:
  ssid: !secret ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$devicename"
    password: !secret ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

mqtt:
    broker: !secret mqtt_broker 
    topic_prefix: esphome/$devicename
    username: !secret mqtt_username
    password: !secret mqtt_password

light:
  - platform: fastled_clockless
    chipset: WS2812
    pin: D2
    num_leds: 20
    rgb_order: BRG
    name: "The Light"
    id: staircase_leds