substitutions:
  devicename: staircase-leds

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

esphome:
  platform: ESP8266
  board: d1_mini

captive_portal:

ota:

mqtt:
  on_message:
    topic: esphome/$devicename/single_led
    qos: 0
    then:
      - light.addressable_set:
          id: staircase_light
          red: 0%
          green: 0%
          blue: 0%
      - light.addressable_set:
          id: staircase_light
          range_from: !lambda return atoi(x.c_str());
          range_to: !lambda return atoi(x.c_str());
          red: 80%
          green: 80%
          blue: 80%

wled:

e131:
  method: multicast

light:
  - platform: neopixelbus
    variant: WS2812
    pin: D2
    num_leds: 100
    type: RGB
    color_correct: [80%, 80%, 80%]
    name: "Staircase Light"
    id: staircase_light
    effects:
      - e131:
          universe: 1
          channels: RGB
      - wled:
          port: 24242
      - addressable_rainbow:
