substitutions:
  devicename: stepper_test

packages:
  wifi: !include fragments/common/wifi.yaml
  device_base: !include fragments/common/device_base.yaml

esphome:
  platform: ESP8266
  board: nodemcuv2

# Enable logging, disable UART
logger:
  baud_rate: 0

mqtt:
  birth_message:
  will_message:
  on_message:
    - topic: esphome/$devicename/the_stepper/cmd
      then:
        - logger.log: "Received stepper command"
        - stepper.report_position:
            id: the_stepper
            position: 0
        - stepper.set_target:
            id: the_stepper
            target: !lambda return atoi(x.c_str());

stepper:
  - platform: a4988
    id: the_stepper
    step_pin: D1
    dir_pin: D2
    max_speed: 1000 steps/s
    acceleration: 1000 steps/s^2
    deceleration: 1000 steps/s^2
    sleep_pin: D0
