substitutions:
    devicename: train_presence

esphome:
  name: $devicename
  platform: ESP8266
  board: nodemcuv2
  build_path: build/$devicename

wifi:
  ssid: !secret ssid
  password: !secret wifi_password
  #use_address: 192.168.144.182
  manual_ip:
    static_ip: 192.168.144.93
    gateway: 192.168.144.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$devicename"
    password: !secret ap_password

# Enable logging
logger:
  baud_rate: 0

ota:

mqtt:
  broker: !secret mqtt_broker 
  topic_prefix: esphome/$devicename
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
  will_message:

binary_sensor:
  - platform: gpio
    name: "$devicename Track Section 1"   
    pin:
      number: D2
      mode: INPUT_PULLUP
    filters:
      - delayed_on_off: 100ms
      - invert:
    on_press:
      - output.turn_off: status_led 
    on_release:
      - output.turn_on: status_led

output:
  - platform: gpio
    id: status_led
    pin: D0
