substitutions:
  devicename: train_presence

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

esphome:
  platform: ESP8266
  board: nodemcuv2

wifi:
  manual_ip:
    static_ip: 192.168.144.93
    gateway: 192.168.144.1
    subnet: 255.255.255.0

# Enable logging, disable uart
logger:
  baud_rate: 0

ota:

binary_sensor:
  - platform: gpio
    name: "$devicename Track Section 1"   
    pin:
      number: D2
      mode: INPUT_PULLUP
    filters:
      - delayed_on_off: 100ms
      - invert:
    on_press:
      - output.turn_off: status_led 
    on_release:
      - output.turn_on: status_led

output:
  - platform: gpio
    id: status_led
    pin: D0
