substitutions:
  devicename: train_presence
  section_1_pin: D0
  section_2_pin: D1
  section_3_pin: D2
  section_4_pin: D3
  section_5_pin: D4
  section_6_pin: D5
  section_7_pin: D6
  section_8_pin: D7

packages:
  wifi: !include fragments/common/wifi.config.yaml
  device_base: !include fragments/common/device_base.config.yaml

esphome:
  platform: ESP8266
  board: nodemcuv2

# Enable logging, disable uart
logger:
  baud_rate: 0

binary_sensor:
  - platform: gpio
    name: "$devicename Track Section 1"   
    pin:
      number: $section_1_pin
    filters:
      - delayed_on_off: 100ms
      - invert:
  - platform: gpio
    name: "$devicename Track Section 2"   
    pin:
      number: $section_2_pin
      mode: INPUT_PULLUP
    filters:
      - delayed_on_off: 100ms
      - invert:
  - platform: gpio
    name: "$devicename Track Section 3"   
    pin:
      number: $section_3_pin
      mode: INPUT_PULLUP
    filters:
      - delayed_on_off: 100ms
      - invert:
  - platform: gpio
    name: "$devicename Track Section 4"   
    pin:
      number: $section_4_pin
      mode: INPUT_PULLUP
    filters:
      - delayed_on_off: 100ms
      - invert:
  - platform: gpio
    name: "$devicename Track Section 5"   
    pin:
      number: $section_5_pin
      mode: INPUT_PULLUP
    filters:
      - delayed_on_off: 100ms
      - invert:
  - platform: gpio
    name: "$devicename Track Section 6"   
    pin:
      number: $section_6_pin
      mode: INPUT_PULLUP
    filters:
      - delayed_on_off: 100ms
      - invert:
  - platform: gpio
    name: "$devicename Track Section 7"   
    pin:
      number: $section_7_pin
      mode: INPUT_PULLUP
    filters:
      - delayed_on_off: 100ms
      - invert:
  - platform: gpio
    name: "$devicename Track Section 8"   
    pin:
      number: $section_8_pin
      mode: INPUT_PULLUP
    filters:
      - delayed_on_off: 100ms
      - invert: