substitutions:
  uuid: 5f781a 
  devicename: watering_$uuid 
  run_duration: 20s
  sleep_duration: 100s

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

esphome:
  platform: ESP32
  board: nodemcu-32s
  # on_boot:
  #   priority: 600
  #   then:
  #     - switch.turn_on: awake
  # on_shutdown:
  #   then:
  #     - switch.turn_off: awake


wifi:
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.144.161
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.144.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

captive_portal:

mqtt:
  topic_prefix: esphome/$devicename
  on_message:
    - topic: esphome/$devicename/ota_mode
      payload: "ON"
      then:
        - deep_sleep.prevent: deep_sleep_1

deep_sleep:
  id: deep_sleep_1
  run_duration: $run_duration 
  sleep_duration: $sleep_duration

globals:
  - id: pump_duration
    type: int
    restore_value: no
    initial_value: "2"

sensor:
  - platform: adc
    pin: 34
    attenuation: 11db
    name: "ground_moisture_1"
    update_interval: 10s
    unit_of_measurement: "%"
    filters:
      - calibrate_linear:
          - 1.75 -> 100
          - 3.91 -> 0
  - platform: adc
    pin: 35
    attenuation: 11db
    name: "ground_moisture_2"
    update_interval: 10s
    unit_of_measurement: "%"
    filters:
      - calibrate_linear:
          - 1.75 -> 100
          - 3.91 -> 0
  - platform: adc
    pin: 32
    attenuation: 11db
    name: "ground_moisture_3"
    update_interval: 10s
    unit_of_measurement: "%"
    filters:
      - calibrate_linear:
          - 1.75 -> 100
          - 3.91 -> 0
  - platform: adc
    pin: 33
    attenuation: 11db
    name: "ground_moisture_4"
    update_interval: 10s
    unit_of_measurement: "%"
    filters:
      - calibrate_linear:
          - 1.75 -> 100
          - 3.91 -> 0
  - platform: adc
    pin: 39 
    id: source_sensor
    update_interval: 10s
    internal: true
  - platform: resistance
    sensor: source_sensor
    configuration: DOWNSTREAM
    resistor: 10kOhm
    name: "brightness"
  - platform: dht
    pin: 14
    model: DHT11
    temperature:
        name: "temperature"
    humidity:
        name: "humidity"
    update_interval: 10s
            
switch:
  - platform: gpio
    id: "awake"
    pin: 21
  - platform: gpio
    id: "pump_1"
    name: "pump_1"
    pin: 17
    on_turn_on:
      - delay: 2s
      - switch.turn_off: pump_1
  - platform: gpio
    id: "pump_2"
    name: "pump_2"
    pin: 5
    on_turn_on:
      - delay: 2s
      - switch.turn_off: pump_2
  - platform: gpio
    id: "pump_3"
    name: "pump_3"
    pin: 18
    on_turn_on:
      - delay: 2s
      - switch.turn_off: pump_3
  - platform: gpio
    id: "pump_4"
    name: "pump_4"
    pin: 19
    on_turn_on:
      - delay: 2s
      - switch.turn_off: pump_4
