substitutions:
    uuid: 7f23a1
    devicename: ledcontroller_$uuid 

packages:
  wifi: !include fragments/common.wifi.config.yaml
  device_base: !include fragments/common.device_base.config.yaml

esphome:
  platform: ESP8266
  board: nodemcuv2

captive_portal:

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D1
    num_leds: 5
    rgb_order: GRB
    name: "WS2812B Light"
    effects:
      - addressable_rainbow:
      - addressable_scan:
          move_interval: 500ms
          scan_width: 1
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:
