substitutions:
  devicename: example-project

packages:
  wifi: !include fragments/common/wifi.config.yaml
  device_base: !include fragments/common/device_base.config.yaml

esphome:
  platform: ESP32
  board: nodemcu-32s
