
mqtt:
  on_message:
  - topic: "esphome/$devicename/notify/${color}"
    then:
    - logger.log:
        level: INFO
        format: "Received new timestamp for ${color}: %s"
        args: ["x.c_str()" ]
        
    - lambda: |-
        time_t end = atoll(x.c_str());
        time_t old = id(pending_notifications)[${index}];
        if (end > old)
        id(pending_notifications)[${index}] = end;

button:
  - platform: template
    name: "Test $color notification"
    on_press:
      - mqtt.publish:
          topic: "esphome/$devicename/notify/$color"
          payload: !lambda |-
            char buf[32]; 
            return itoa(id(sntp_time).now().timestamp + 30, buf, 10);